services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=1234
      - BUNDLE_WITHOUT=development
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      redis:
        condition: service_healthy
    command: >
      bash -c "
      bundle config unset without &&
      bundle config set --local without 'development' &&
      bundle install &&
      exec ./docker-entrypoint.sh bundle exec ruby app.rb
      "

volumes:
  redis_data:
  bundle_cache:
